# Central tmux-powerline config for Kali / pentest / bug bounty.

KP_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-powerline/core"
KP_CURRENT_THEME_FILE="$KP_DIR/current_theme"
KP_SETTINGS_FILE="$KP_DIR/settings.sh"

[ -r "$KP_SETTINGS_FILE" ] && . "$KP_SETTINGS_FILE"

if [ -r "$KP_CURRENT_THEME_FILE" ]; then
  export TMUX_POWERLINE_THEME="$(cat "$KP_CURRENT_THEME_FILE")"
else
  export TMUX_POWERLINE_THEME="darkvoid"
fi

export TMUX_POWERLINE_STATUS_VISIBILITY="on"
export TMUX_POWERLINE_STATUS_INTERVAL="2"
export TMUX_POWERLINE_STATUS_JUSTIFICATION="centre"
export TMUX_POWERLINE_STATUS_LEFT_LENGTH="90"
export TMUX_POWERLINE_STATUS_RIGHT_LENGTH="95"
export TMUX_POWERLINE_WINDOW_STATUS_SEPARATOR=""

export TMUX_POWERLINE_SEG_HOSTNAME_FORMAT="short"
export TMUX_POWERLINE_SEG_PWD_MAX_LEN="34"

export TMUX_POWERLINE_SEG_VPN_DISPLAY_MODE="both"
export TMUX_POWERLINE_SEG_VPN_NICS="^tun0$ ^tun1$ ^wg0$ ^ppp0$ ^tap0$"
export TMUX_POWERLINE_SEG_VPN_SYMBOL="vpn "

export TMUX_POWERLINE_SEG_LAN_IP_SYMBOL="ⓛ "
export TMUX_POWERLINE_SEG_WAN_IP_SYMBOL="ⓦ "

export TMUX_POWERLINE_SEG_VCS_BRANCH_MAX_LEN="22"
export TMUX_POWERLINE_SEG_VCS_BRANCH_DEFAULT_SYMBOL="�"

export TMUX_POWERLINE_SEG_MODE_INDICATOR_NORMAL_AND_PREFIX_MODE_ENABLED="true"
export TMUX_POWERLINE_SEG_MODE_INDICATOR_NORMAL_MODE_TEXT="N"
export TMUX_POWERLINE_SEG_MODE_INDICATOR_PREFIX_MODE_TEXT="PFX"
export TMUX_POWERLINE_SEG_MODE_INDICATOR_MOUSE_MODE_ENABLED="true"
export TMUX_POWERLINE_SEG_MODE_INDICATOR_MOUSE_MODE_TEXT="MOUSE"
export TMUX_POWERLINE_SEG_MODE_INDICATOR_COPY_MODE_ENABLED="true"
export TMUX_POWERLINE_SEG_MODE_INDICATOR_COPY_MODE_TEXT="COPY"
export TMUX_POWERLINE_SEG_MODE_INDICATOR_SEPARATOR_TEXT=" "

export TMUX_POWERLINE_SEG_TIME_FORMAT="%H:%M"
export TMUX_POWERLINE_SEG_UTC_TIME_FORMAT="%H:%M UTC"
export TMUX_POWERLINE_SEG_DATE_FORMAT="%Y-%m-%d"

export TMUX_POWERLINE_SEG_IFSTAT_INTERFACE_EXCLUDES="^lo$ ^docker.*$ ^br-.*$ ^veth.*$"
